name: CMake Build
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - cmake

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # This action checks-out the repository under $GITHUB_WORKSPACE, so the workflow can access it.
      - name: checkout
        uses: actions/checkout@v2
      - name: sudo apt install libpcsclite-dev check
        run: sudo apt install libpcsclite-dev check
      #- name: sudo find / -name "*libpcsclite*"
      #  run: sudo find / -name "*libpcsclite*"
      - name: mkdir cmake_build
        run: mkdir cmake_build
      - name: cd cmake_build; cmake .. -DVERBOSE_CMAKE=ON -DENABLE_GCC_WARN=ON
        run: |
          cd cmake_build
          cmake .. -DVERBOSE_CMAKE=ON -DENABLE_GCC_WARN=ON
      - name: make
        run: make
      - name: make test
        run: make test