name: CMake Build
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - cmake

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # This action checks-out the repository under $GITHUB_WORKSPACE, so the workflow can access it.
      - name: checkout
        uses: actions/checkout@v2
      - name: run cmake
        run: |
          mkdir cmake_build
          cd cmake_build
          cmake .. -DVERBOSE_CMAKE=ON -DENABLE_GCC_WARN=ON
          make
          make test